### ISSUE TITLE
Create a smoothies API

### ISSUE THREAD

**Issue by stanleycyang** [syang019/Smoothies_API#1]
Endpoint: localhost:3000/api/smoothies

[
{id: 1, name: "banana blast"}
]

Endpoint: localhost:3000/api/smoothies/1

{
name: "banana blast",
calories: "540,
protein: "15g",
sugars: "30g",
fruits: [
{name: "banana, id: 1}
{name: "strawberry", id: 2}
]
}

**Comment by RobAWilkinson** [comment]
I converted the calories and proteins and sugars to be integers rathen than strings
